default: llava_med

models:
  huatuo:
    local_or_hf_id: /home/dbw/models/HuatuoGPT-Vision-7B
    backend: huatuo

  llava_med:
    hf_id: microsoft/llava-med-v1.5-mistral-7b
    backend: llava_med
    conversation: vicuna_v1

  hulu_med:
    local_or_hf_id: Hulu-Med
    backend: hulu_med

  llava_1_6:
    local_or_hf_id: /home/dbw/models/llava-v1.6-vicuna-7b
    backend: llava_next
    conversation: vicuna_v1

  qwen2_5_vl:
    local_or_hf_id: /home/dbw/models/Qwen2.5-VL-7B-Instruct
    backend: qwen2_5_vl

download:
  hf_endpoint: https://hf-mirror.com
  cache_dir: hf_cache
